/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package connectfour;
//import view.connectFourPrototype.ConnectFourPrototype;
//import view.connectFourPrototype.NewGamePrototype;
import view.connectFourPrototype.*;

public class App {
    public static void main(String[] args) {
        ConnectFourPrototype.main(args);
        NewGamePrototype.main(args);
        InitialStatePrototype.main(args);
    }
}
